version: '3'

services:
  ds-star-postgres:
    image: postgres:17
    container_name: ds-star-postgres
    restart: "always"

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "ds-star"

    volumes:
      - "./db:/var/lib/postgresql/data"

    networks:
      - dsstar_network

networks:
  dsstar_network:
